server:
  port: 8888
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false